/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';
import { Language } from './language';
import { Gender } from './gender';
import { Lock } from './lock';


export interface Client { 
    lock: Lock;
    name: string;
    lastname: string;
    isCompany: boolean;
    mail1: string;
    mail2: string;
    tel1: string;
    tel2: string;
    vat_number: string;
    fiscal_code: string;
    codice_destinatario: string;
    pec: string;
    esigibilita_iva: string;
    publica_amministrazione: boolean;
    cup: string;
    cig: string;
    address: Address;
    id: number;
    gender?: Gender;
    language: Language;
    fullname?: string;
}

