/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserEssential } from './userEssential';
import { DeliveryNoteReason } from './deliveryNoteReason';
import { DescriptiveArticle } from './descriptiveArticle';
import { Job } from './job';
import { Lock } from './lock';


export interface DeliveryNote { 
    lock: Lock;
    number: number;
    date: string;
    name: string;
    company_address: string;
    delivery_address: string;
    variations: string;
    weight: string;
    freight: boolean;
    free: boolean;
    assigned: boolean;
    id: number;
    user: UserEssential;
    articles: Array<DescriptiveArticle>;
    timestamp: string;
    job?: Job;
    pdf?: string;
    delivery_note_reason: DeliveryNoteReason;
}

