/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DescriptiveArticleCreate } from './descriptiveArticleCreate';


export interface DeliveryNoteCreate { 
    number: number;
    date: string;
    name: string;
    company_address: string;
    delivery_address: string;
    variations: string;
    weight: string;
    freight: boolean;
    free: boolean;
    assigned: boolean;
    articles: Array<DescriptiveArticleCreate>;
    job_id: number;
    delivery_note_reason_id: number;
}

