/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DescriptiveArticleCreate { 
    name: string;
    amount: number;
    description: string;
    single_price: number;
    discount: number;
    alternative: boolean;
    descriptive_articles?: Array<DescriptiveArticleCreate>;
    vat_id: number;
    unit_id?: number;
}

