/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JobStatus } from './jobStatus';
import { UserEssential } from './userEssential';
import { Address } from './address';
import { OrderableType } from './orderableType';
import { Client } from './client';
import { Lock } from './lock';


export interface Job { 
    type: OrderableType;
    name: string;
    id: number;
    displayable_name: string;
    lock: Lock;
    description: string;
    timestamp: string;
    year: number;
    code: string;
    client: Client;
    address: Address;
    archive: boolean;
    path: string;
    status: JobStatus;
    sub_jobs: Array<Job>;
    is_main: boolean;
    is_sub: boolean;
    is_mini: boolean;
    responsible: UserEssential;
}

