/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export type JobStatusType = 'JOBSTATUS_CREATED' | 'JOBSTATUS_ACCEPTED' | 'JOBSTATUS_COMPLETED' | 'JOBSTATUS_DECLINED';

export const JobStatusType = {
    Created: 'JOBSTATUS_CREATED' as JobStatusType,
    Accepted: 'JOBSTATUS_ACCEPTED' as JobStatusType,
    Completed: 'JOBSTATUS_COMPLETED' as JobStatusType,
    Declined: 'JOBSTATUS_DECLINED' as JobStatusType
};

