/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export type JobTypeType = 'JOBTYPE_MAIN' | 'JOBTYPE_SUB' | 'JOBYTPE_MINI';

export const JobTypeType = {
    JobtypeMain: 'JOBTYPE_MAIN' as JobTypeType,
    JobtypeSub: 'JOBTYPE_SUB' as JobTypeType,
    JobytpeMini: 'JOBYTPE_MINI' as JobTypeType
};

