/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export type OrderableType = 'job' | 'stock' | 'supplier';

export const OrderableType = {
    Job: 'job' as OrderableType,
    Stock: 'stock' as OrderableType,
    Supplier: 'supplier' as OrderableType
};

