/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Payment } from './payment';
import { Reminder } from './reminder';
import { DescriptiveArticle } from './descriptiveArticle';
import { Vat } from './vat';
import { Lock } from './lock';


export interface OutgoingInvoice { 
    lock: Lock;
    number: string;
    date: string;
    payment_condition: string;
    payment_date: string;
    id: number;
    timestamp: string;
    pdf?: string;
    payments: Array<Payment>;
    descriptive_articles: Array<DescriptiveArticle>;
    reminders: Array<Reminder>;
    vat: Vat;
    job_id: number;
    full_price_without_vat: number;
    full_vat_amount: number;
    full_price_with_vat: number;
    client_name: string;
    paid: boolean;
}

