/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Payment } from './payment';
import { Reminder } from './reminder';
import { OrderedArticle } from './orderedArticle';
import { Lock } from './lock';


export interface OutgoingInvoice { 
    lock: Lock;
    number: string;
    date: string;
    in_price_included: string;
    in_price_excluded: string;
    payment_text: string;
    delivery: string;
    id: number;
    timestamp: string;
    pdf?: string;
    payment?: Payment;
    articles: Array<OrderedArticle>;
    reminders: Array<Reminder>;
}

