/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaintCreate } from './paintCreate';
import { ExpenseCreate } from './expenseCreate';
import { WoodListCreate } from './woodListCreate';


export interface RecalculationUpdate { 
    pdf?: string;
    material_charge_percent: number;
    expenses: Array<ExpenseCreate>;
    paints: Array<PaintCreate>;
    wood_lists: Array<WoodListCreate>;
}

