/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Order } from './order';
import { WoodList } from './woodList';
import { Expense } from './expense';
import { Paint } from './paint';
import { Lock } from './lock';
import { Workload } from './workload';


export interface Recalculation { 
    lock: Lock;
    pdf?: string;
    material_charge_percent: number;
    id: number;
    orders: Array<Order>;
    workloads: Array<Workload>;
    expenses: Array<Expense>;
    paints: Array<Paint>;
    wood_lists: Array<WoodList>;
    total_sum: number;
}

