/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export type ReminderLevel = 'REMINDER_LEVEL.ZE' | 'REMINDER_LEVEL.LEVEL1' | 'REMINDER_LEVEL.LEVEL2' | 'REMINDER_LEVEL.LEVEL3';

export const ReminderLevel = {
    Ze: 'REMINDER_LEVEL.ZE' as ReminderLevel,
    Level1: 'REMINDER_LEVEL.LEVEL1' as ReminderLevel,
    Level2: 'REMINDER_LEVEL.LEVEL2' as ReminderLevel,
    Level3: 'REMINDER_LEVEL.LEVEL3' as ReminderLevel
};

