/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export type ReminderLevel = '1' | '2' | '3' | '4';

export const ReminderLevel = {
    _1: '1' as ReminderLevel,
    _2: '2' as ReminderLevel,
    _3: '3' as ReminderLevel,
    _4: '4' as ReminderLevel
};

