/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Right } from './right';


export interface User { 
    email: string;
    tel: string;
    firstname: string;
    secondname: string;
    cost: number;
    id: number;
    fullname: string;
    handy: string;
    dial: string;
    disabled?: boolean;
    rights?: Array<Right>;
    employee: boolean;
    office: boolean;
}

