/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserCreate { 
    email: string;
    tel: string;
    firstname: string;
    secondname: string;
    cost: number;
    password: string;
    handy: string;
    dial: string;
    employee: boolean;
    office: boolean;
    hours: boolean;
    chat: boolean;
    position: string;
}

