/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserEssential } from './userEssential';
import { WorkPhase } from './workPhase';
import { Expense } from './expense';
import { Drive } from './drive';
import { JobSection } from './jobSection';
import { AdditionalWorkload } from './additionalWorkload';
import { EatingPlace } from './eatingPlace';


export interface WorkDay { 
    id: number;
    date: string;
    user: UserEssential;
    job_sections: Array<JobSection>;
    expenses: Array<Expense>;
    drives: Array<Drive>;
    work_phases: Array<WorkPhase>;
    finished: boolean;
    eating_place?: EatingPlace;
    additional_workloads: Array<AdditionalWorkload>;
    length_minutes: number;
}

